### ISSUE TITLE
Doesn't work with Lumen 5.2

### ISSUE THREAD

**Issue by yushine** [webNeat/lumen-generators#10]
composer require wn/lumen-generators
Using version ^1.1 for wn/lumen-generators
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing wn/lumen-generators (1.1.1)
  Loading from cache

Generating autoload files

```

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        if ($this->app->environment() == 'local') {
            $this->app->register('Wn\Generators\CommandsServiceProvider');
        }
    }
}

```

After that run `php artisan list`

Doesn't show any WN commands.

If run 'php artisan wn:resource`, show below:

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "wn" namespace.
```

**Comment by yushine** [comment]
It works after add `$app->register('Wn\Generators\CommandsServiceProvider');` to `bootstrap/app.php`
Sorry.

**Comment by jhkueh** [comment]
Need to make sure that `$app->register(App\Providers\AppServiceProvider::class);` is uncommented.
