### ISSUE TITLE
Check existence of file

### ISSUE THREAD

**Issue by henninghorn** [webNeat/lumen-generators#11]
Hi @webNeat 

Would it make sense that the generator would check the existence of a file before creating it?
Like if you're generating a model, so you accidentally don't overwrite a existing model.

**Comment by webNeat** [comment]
Hello, 

yes this could definitely help. An option `--force` could be added to force to override the existing file.

I will try to include this in the next release :)

Thank you

**Comment by webNeat** [comment]
Added https://github.com/webNeat/lumen-generators/releases/tag/1.2.0
