### ISSUE TITLE
[ErrorException]   Undefined index: factory on php artisan wn:resources

### ISSUE THREAD

**Issue by KevinBeckers** [webNeat/lumen-generators#14]
Hey,

I am getting a [ErrorException] Undefined index: factory on php artisan wn:resources generator.yml
I am using lumen 5.2.

Thanks

**Comment by webNeat** [comment]
Hello,

Can you please share your `generator.yml` file to help me investigate the issue ?

Thanks for using these generators

**Comment by KevinBeckers** [comment]
The file is in pastebin:
[Yaml](http://pastebin.com/XRupHPvR)

Thanks in advance

**Comment by webNeat** [comment]
It seems to be a bug in the code. This will be fixed in the next release 2.0

**Comment by KevinBeckers** [comment]
Thx!

**Comment by beechit** [comment]
when is next release planned / this bug fixed ?

**Comment by SolomonBR** [comment]
here's how to fix it, update \vendor\wn\lumen-generators\src\Commands\ResourcesCommand.php
around line 109 with this:

```
protected function serializeField($field)
{
    $name = $field['name'];
    $schema = $this->convertArray(str_replace(':', '.', $field['schema']), ' ', ':');
    $rules = (isset($field['rules'])) ? trim($field['rules']) : '';
    if(isset($field['tags'])) {
        $tags = $this->convertArray($field['tags'], ' ', ',');
    } else {
        $tags = '';
    }

    $string = "{$name};{$schema};{$rules};{$tags}";

    if(isset($field['factory'])){
        $string .= ';' . $field['factory'];
    }

    return $string;
}
```

**Comment by capaci** [comment]
Same using Lumen 5.3  :(
