### ISSUE TITLE
Disabling timestamps in wn:resource

### ISSUE THREAD

**Issue by denizdogan** [webNeat/lumen-generators#15]
Is there any way to generate resources with `public $timestamps = false;` on the models and similar for the migration?

**Comment by webNeat** [comment]
Hello,

I am working on version 2.0 of the generators and I will try to make it possible :smile:

**Comment by TCB13** [comment]
@webNeat any timeline for this version 2.0? Thank you!

**Comment by webNeat** [comment]
Hello @TCB13 , I have just released [version 1.2.0](https://github.com/webNeat/lumen-generators/releases/tag/1.2.0) But unfortunately I didn't include this feature as there was others requested before.

**Comment by TCB13** [comment]
@webNeat thanks for the update, I'll be waiting for this feature on a next release, this would be really helpful!

**Comment by webNeat** [comment]
[version 1.3.0](https://github.com/webNeat/lumen-generators/releases/tag/1.3.0) released containing this feature. Enjoy!

**Comment by TCB13** [comment]
@webNeat awesome! you rock! Was this documented?

**Comment by webNeat** [comment]
Yes sure, I updated the README.

In summary:

- to generate a model without timestamps you do:

```
wn:model ... --timestamps=false
```

- migrations are generated without additional columns by default now. when needed, these columns (including timestamps) can be specified using the `--add` option:

```
wn:migration ... --add=timestamps,softDeletes
```

- the same `--add` option was added to `wn:resource` as well as the yaml structure for `wn:resources`
