### ISSUE TITLE
Update for lumen 5.3

### ISSUE THREAD

**Issue by devSarry** [webNeat/lumen-generators#21]
Routs in 5.3 have moved wn:routes gives an error 

```bash
  [Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path ./app/Http/routes.php
```

**Comment by webNeat** [comment]
Lumen 5.3.x is now supported.
adding new release soon

**Comment by webNeat** [comment]
[version 1.3.0](https://github.com/webNeat/lumen-generators/releases/tag/1.3.0) released !

**Comment by sajadghawami** [comment]
Still had an issue with this, had to change in `/src/Commands/RouteCommands` line from:

`$routesPath = './routes/web.php';`

to 

`$routesPath = '../routes/web.php';`

And having that same issue for some other file paths... 

Why not an absolute path? Something like:

`$routesPath = $_SERVER['DOCUMENT_ROOT'] . '/routes/web.php';`
