### ISSUE TITLE
Pivots not Generating through Yaml

### ISSUE THREAD

**Issue by esuveyke** [webNeat/lumen-generators#4]
Seems the pivot table migrations are not being created due to line 38:ResourcesCommand.php

theres a dd(...)

was there a reason why this was placed here?

**Comment by webNeat** [comment]
I was just debugging and forgot to remove this line before pushing :P 

It is fixed now. I added a new release with that fix https://github.com/webNeat/lumen-generators/releases/tag/1.1.1

Thanks for reporting the bug and please let me know if you found any other bug

**Comment by esuveyke** [comment]
ive introduce this project in to our app gen workflow.  we will let you know as we find issues or ideas.

One that comes to mind, is there a way to set the namespace from the Yaml?

**Comment by webNeat** [comment]
This is a nice idea, I will try to include it in the next release.

**Comment by webNeat** [comment]
I am closing this issue as the first issue is fixed.
I opened a new issue for "the namespace from the Yaml": https://github.com/webNeat/lumen-generators/issues/18
