### ISSUE TITLE
There are no commands defined in the "wn" namespace.

### ISSUE THREAD

**Issue by commadore** [webNeat/lumen-generators#5]
I followed the install, I'm getting:
There are no commands defined in the "wn" namespace
when using and wn command.
List doesn't show the wn commands.

Do I need to add to the app/console/Kernal class?

**Comment by webNeat** [comment]
Hello,
- Are you using this package with Laravel 5 or Lumen ? 
- What is the output of `php artisan list` ?

**Comment by commadore** [comment]
Latest lumen.

Just shows the default artisan command list
`Laravel Framework version Lumen (5.2.5) (Laravel Components 5.2.*)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help              Displays help for a command
  list              Lists commands
  migrate           Run the database migrations
 cache
  cache:clear       Flush the application cache
 db
  db:seed           Seed the database with records
 make
  make:migration    Create a new migration file
 migrate
  migrate:install   Create the migration repository
  migrate:refresh   Reset and re-run all migrations
  migrate:reset     Rollback all database migrations
  migrate:rollback  Rollback the last database migration
  migrate:status    Show the status of each migration
 queue
  queue:failed      List all of the failed queue jobs
  queue:flush       Flush all of the failed queue jobs
  queue:forget      Delete a failed queue job
  queue:listen      Listen to a given queue
  queue:restart     Restart queue worker daemons after their current job
  queue:retry       Retry a failed queue job
  queue:work        Process the next job on a queue
 schedule
  schedule:run      Run the scheduled commands`

**Comment by webNeat** [comment]
make sure that you uncomment the following lines in the `bootstrap/app.php` file

```
$app->withFacades();
$app->withEloquent();

$app->register(App\Providers\AppServiceProvider::class);
```

your file should look like [app.php](https://github.com/webNeat/lumen-generators/blob/master/lumen-test/bootstrap/app.php)

**Comment by commadore** [comment]
Already had those, my app.php is the same as yours.

My Steps were:
1. composer create-project --prefer-dist laravel/lumen myProject
2. cd myProject
3. composer require wn/lumen-generators
4. Made changes to app.php and app/Providers/AppServiceProvider.php
5. php artisan list

Can you see anything obviously wrong there?

**Comment by webNeat** [comment]
Thanks for details, well my only guess is that you don't have a `.env` file in your project specifying that you working in local. Because as you notice in the `app/Providers/AppServiceProvider.php` the generators are registered only if you're in the local environment.

Just rename the `.env.example` file as `.env` and it should work.

I will add this notice to the README

**Comment by commadore** [comment]
It's executing that code for definite. Still no joy.
I'm going to try it on a different server, see if its something like that causing the problem.

**Comment by commadore** [comment]
Confirmed that on a different env it's working fine.
For reference I was using cloud9 (https://c9.io/) as the environment.
I'll have a chat with them, really appreciate your time, thanks

**Comment by delicacyyy** [comment]
$app->register(App\Providers\AppServiceProvider::class); 
this statement should update to README.MD
